#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 28 16:31:10 2022

@author: ghiggi
"""
import numpy as np
import xarray as xr 

def xr_sel_coords_between(data, **kwargs):
    """It enable to slice xarray object by dimension value.
    
    This is absolutely required when the dimension are not increasing.
    Example: The Northing coordinates of CH1903 CRS decreases along y.
    """
    for k, slc in kwargs.items():
        if not isinstance(slc, slice):
             raise TypeError("Expects slice objects.")
        # TODO check coord is 1 dim and exist 
        if k not in data.dims:
            raise ValueError("Argument should be a dimension of the data object.")
        if len(data[k].shape) > 1:
            raise ValueError("Dimension should be 1-D.")
        if slc.stop >= slc.start:
            data = data.sel({k: slc})
        else:
            isel_idx = np.where(np.logical_and(data[k].data > slc.stop, data[k].data <= slc.start))[0]
            data = data.isel({k: isel_idx})
    return data 